apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app
spec:
  replicas: 2 #Run 2 copies of my app at the same time. If one crashes the other is still running — no downtime!
  selector:
    matchLabels:
      app: flight-app
  template:
    metadata:
      labels:
        app: flight-app
    spec:
      containers:
      - name: flight-app
        image: flight_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000