apiVersion: v1
kind: Service
metadata:
  name: flight-app-service
spec:
  selector:
    app: flight-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
    